services:
  app:
    build: . 
    container_name: fxql-app
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    command: /bin/sh -c "yarn run db:migrate && yarn run db:generate && yarn run start:dev"
      - /bin/sh
      - -c


  postgres:
    image: postgres:13
    restart: always
    env_file:
      - .env
    container_name: fxql-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
